### ISSUE TITLE
Mutate does not refresh seed on use - causing converging behavior

### ISSUE THREAD

**Issue by jasonjmcghee** [raysan5/rfxgen#18]
Hi there!

I've used `sfxr` for a while, so I was surprised by the converging behavior of the "Mutate" button in `rfxgen`.

This can be reproduced by repeatedly pressing "Mutate".
Notice how the applied mutations are monotonic.
After a certain number of presses, the audio no longer changes.

Compare this behavior to `sfxr` which can mutate in either direction (and dramatically different magnitudes) and does not converge.

**Comment by raysan5** [comment]
@jasonjmcghee thanks for reporting and excuse the late response. I've been investigating this issue but I couldn't find the cause yet, it could be related to rounding issues with float vs double but not sure... The problem is located in `GenerateWave()` but I couldn't find it yet. 

Help is welcome.
