### ISSUE TITLE
Can't save sfx files

### ISSUE THREAD

**Issue by EJSainz** [raysan5/rfxgen#3]
On Windows 10, when using the version downloaded from itch.io .

I've been saving a lot of files, but when I wanted to load none of them was there :-( .

**Comment by raysan5** [comment]
That's very weird! You mean saving `.rfx` files? Maybe saving in a protected system folder? Please, could you provide some more info?

**Comment by EJSainz** [comment]
Now that you mention it, I was saving to a subfolder in the desktop. The strange thing here is that exporting the wav files to the same folder works like charm.

**Comment by EJSainz** [comment]
And yep, I mean .rfx, sorry :-) .

**Comment by wesleyParriott** [comment]
This is related but it may be it's own bug.
I'm Windows Seven with a 650 ti and an i3. I'm using the embedded sound  card. 

When I go to save my sound as a different name than the default name it doesn't save properly. What happens is that rFXGen will either save it to disk but named "sound.rfx" (rather than the name I gave it) or if there is already a "sound.rfx" in that directory than it will won't save at all.

**Comment by raysan5** [comment]
Corrected in commit https://github.com/raysan5/rfxgen/commit/2e67a45d69757cef456b0453c8bd1a8bcc7f6312
